<?php

namespace App\Console\Commands;

use App\Domain\Election\Enum\ElectionLifecycleState;
use Illuminate\Console\Command;

class ExportLifecycleVocabulary extends Command
{
    protected $signature = 'governance:export-lifecycle-vocabulary';
    protected $description = 'Generate resources/js/Constants/ElectionLifecycleStates.ts from PHP enum';

    public function handle(): void
    {
        $cases = ElectionLifecycleState::cases();

        $constants = collect($cases)->map(function ($case) {
            $key = strtoupper(preg_replace('/(?<!^)[A-Z]/', '_$0', $case->name));
            return "  {$key}: '{$case->value}',";
        })->implode("\n");

        $content = <<<TS
/**
 * @generated by: php artisan governance:export-lifecycle-vocabulary
 * @source: App\\Domain\\Election\\Enum\\ElectionLifecycleState
 *
 * DO NOT EDIT MANUALLY. Re-run the artisan command to regenerate.
 * These are constitutional lifecycle states — NOT UI phases.
 * For UI phase grouping, see ElectionPhase in ElectionPhaseService.ts.
 */
export const ElectionLifecycleStates = {
{$constants}
} as const

export type ElectionLifecycleState = typeof ElectionLifecycleStates[keyof typeof ElectionLifecycleStates]
TS;

        file_put_contents(resource_path('js/Constants/ElectionLifecycleStates.ts'), $content);

        $this->info('Generated: resources/js/Constants/ElectionLifecycleStates.ts');
        $this->line(sprintf('  %d states exported from ElectionLifecycleState enum.', count($cases)));
    }
}
