/**
 * @generated by: php artisan governance:export-lifecycle-vocabulary
 * @source: App\Domain\Election\Enum\ElectionLifecycleState
 *
 * DO NOT EDIT MANUALLY. Re-run the artisan command to regenerate.
 * These are constitutional lifecycle states — NOT UI phases.
 * For UI phase grouping, see ElectionPhase in ElectionPhaseService.ts.
 */
export const ElectionLifecycleStates = {
  DRAFT: 'draft',
  SUBMITTED_FOR_APPROVAL: 'submitted_for_approval',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  SETUP_ADMINISTRATION: 'setup_administration',
  SETUP_NOMINATION: 'setup_nomination',
  READY_FOR_VOTING: 'ready_for_voting',
  VOTING_ACTIVE: 'voting_active',
  COUNTING: 'counting',
  RESULTS_PUBLISHED: 'results_published',
  ARCHIVED: 'archived',
  SUSPENDED: 'suspended',
} as const

export type ElectionLifecycleState = typeof ElectionLifecycleStates[keyof typeof ElectionLifecycleStates]